[project]
name = "mars"
version = "0.1.0"
description = ""
authors = [
    {name = "Noe Javet",email = "np.javet@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi[standard] (>=0.115.12,<0.116.0)",
    "python-docx (>=1.1.2,<2.0.0)",
    "langchain (>=0.3.23,<0.4.0)",
    "langchain-ollama (>=0.3.2,<0.4.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
mars = "mars.main:run_app"

[tool.poetry.group.dev.dependencies]
httpx = {extras = ["http2"], version = "^0.28.1"}
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"

